animal_controller:
    resource: ../src/Animals/Infrastructure/HttpController/
    type: annotation
    prefix: /animals
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
